[build]
base = "."
command = "npm run build"
public = "./build/"

[build.environment]
REACT_APP_API_USER_URL = "http://localhost:8082"
REACT_APP_API_AUTH_URL = "http://localhost:8081"
REACT_APP_API_ORDER_URL = "http://localhost:8080"